"""initial canonical GBO schema + seed data.

Creates the full canonical data model (doc 20) and seeds the data-driven
registries and the built-in file importer:

* the built-in ``file_import`` :class:`SourceDescriptor` (LIN-R1.1), and
* the ``SEED_SPORTS`` sport-registry rows (GBO-R16a) plus an ``other`` sub-sport
  fallback per sport (GBO-R16a-ii).

PORTABLE (GBO-R8b): every DDL statement here emits only the portable types the
column factories produce — ``sa.Uuid``, ``sa.Enum(native_enum=False, create_constraint=True)`` (text + CHECK,
NOT a native PG ENUM), portable ``sa.JSON``, ``sa.DateTime(timezone=True)`` — so the
same revision runs unchanged on SQLite / PostgreSQL / MariaDB (DSN-only difference).
Batch mode keeps the (SQLite-absent) ALTERs portable without code change.

Revision ID: 0001
Revises:
Create Date: 2026-06-06 13:42:42.385271+00:00
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from wattwise_core.domain.enums import SEED_SPORTS
from wattwise_core.persistence.types import utcnow


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Stable id for the single built-in OSS file-importer source descriptor (LIN-R1.1).
# Fixed (not random) so the seed is deterministic and the downgrade can target it.
FILE_IMPORT_SOURCE_DESCRIPTOR_ID = uuid.UUID("01890000-0000-7000-8000-000000000001")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_descriptor',
    sa.Column('source_descriptor_id', sa.Uuid(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('oauth_api', 'file_upload', 'webhook', 'scrape', name='sourcekind', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('trust_profile', sa.JSON(), nullable=False),
    sa.Column('default_fidelity', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_descriptor_id', name=op.f('pk_source_descriptor')),
    sa.UniqueConstraint('source_key', name='uq_source_descriptor_source_key')
    )
    op.create_table('sport',
    sa.Column('sport_code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('has_mechanical_power', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sport_code', name=op.f('pk_sport'))
    )
    op.create_table('stream_channel',
    sa.Column('stream_channel_id', sa.Uuid(), nullable=False),
    sa.Column('stream_set_id', sa.Uuid(), nullable=False),
    sa.Column('set_kind', sa.Enum('activity', 'wellness', name='streamsetkind', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('channel', sa.Enum('power_w', 'hr_bpm', 'cadence_rpm', 'speed_mps', 'altitude_m', 'distance_m', 'latlng', 'temp_c', 'left_right_balance', 'smo2', 'core_temp_c', 'respiration_rpm', 'rr_intervals_ms', name='streamchannelname', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('sample_basis', sa.Enum('time', 'distance', 'event', name='samplebasis', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('stream_channel_id', name=op.f('pk_stream_channel')),
    sa.UniqueConstraint('stream_set_id', 'channel', name='uq_stream_channel_set_channel')
    )
    with op.batch_alter_table('stream_channel', schema=None) as batch_op:
        batch_op.create_index('ix_stream_channel_stream_set_id', ['stream_set_id'], unique=False)

    op.create_table('athlete',
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('sex', sa.Enum('female', 'male', 'other', 'unknown', name='sex', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('body_mass_kg', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('primary_locale', sa.String(length=35), nullable=True),
    sa.Column('current_sport', sa.String(length=64), nullable=True),
    sa.Column('reference_timezone', sa.String(length=64), nullable=False),
    sa.Column('reference_timezone_effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_training_load_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_sport'], ['sport.sport_code'], name=op.f('fk_athlete_current_sport_sport')),
    sa.PrimaryKeyConstraint('athlete_id', name=op.f('pk_athlete'))
    )
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_current_sport'), ['current_sport'], unique=False)

    op.create_table('sub_sport',
    sa.Column('sub_sport_code', sa.String(length=64), nullable=False),
    sa.Column('sport_code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sport_code'], ['sport.sport_code'], name=op.f('fk_sub_sport_sport_code_sport')),
    sa.PrimaryKeyConstraint('sub_sport_code', name=op.f('pk_sub_sport'))
    )
    with op.batch_alter_table('sub_sport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_sport_sport_code'), ['sport_code'], unique=False)

    op.create_table('activity',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time_local', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_time_s', sa.Integer(), nullable=True),
    sa.Column('moving_time_s', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=64), nullable=False),
    sa.Column('sub_sport', sa.String(length=64), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_work_j', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('energy_kj', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('avg_power_w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_power_w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('avg_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('avg_cadence_rpm', sa.SmallInteger(), nullable=True),
    sa.Column('avg_speed_mps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('elevation_gain_m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('avg_temp_c', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('training_effect_aerobic', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('anaerobic_effect', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('vo2max_estimate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('training_load_source', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('device_class', sa.Enum('powermeter', 'trainer', 'gps_watch', 'phone', 'estimated', 'unknown', name='deviceclass', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('has_power', sa.Boolean(), nullable=False),
    sa.Column('has_hr', sa.Boolean(), nullable=False),
    sa.Column('has_gps', sa.Boolean(), nullable=False),
    sa.Column('has_cadence', sa.Boolean(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_activity_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['sport'], ['sport.sport_code'], name=op.f('fk_activity_sport_sport')),
    sa.ForeignKeyConstraint(['sub_sport'], ['sub_sport.sub_sport_code'], name=op.f('fk_activity_sub_sport_sub_sport')),
    sa.PrimaryKeyConstraint('activity_id', name=op.f('pk_activity'))
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_activity_athlete_sport_start_time', ['athlete_id', 'sport', 'start_time'], unique=False)
        batch_op.create_index('ix_activity_athlete_start_time', ['athlete_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_sub_sport'), ['sub_sport'], unique=False)

    op.create_table('connection',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('source_descriptor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('connected', 'reauth_required', 'error', 'disconnected', name='connectionstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('credential_ref', sa.String(length=512), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_archetype', sa.Enum('oauth_redirect', 'api_key', 'credentials', 'file_upload', name='autharchetype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_connection_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['source_descriptor_id'], ['source_descriptor.source_descriptor_id'], name=op.f('fk_connection_source_descriptor_id_source_descriptor')),
    sa.PrimaryKeyConstraint('connection_id', name=op.f('pk_connection')),
    sa.UniqueConstraint('athlete_id', 'source_descriptor_id', name='uq_connection_athlete_source')
    )
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_connection_athlete_source', ['athlete_id', 'source_descriptor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connection_source_descriptor_id'), ['source_descriptor_id'], unique=False)

    op.create_table('daily_wellness',
    sa.Column('daily_wellness_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('resting_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('min_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('stress_avg', sa.SmallInteger(), nullable=True),
    sa.Column('stress_max', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_high', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_low', sa.SmallInteger(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_s', sa.Integer(), nullable=True),
    sa.Column('highly_active_s', sa.Integer(), nullable=True),
    sa.Column('sedentary_s', sa.Integer(), nullable=True),
    sa.Column('active_kcal', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bmr_kcal', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_kcal', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('intensity_minutes_moderate', sa.SmallInteger(), nullable=True),
    sa.Column('intensity_minutes_vigorous', sa.SmallInteger(), nullable=True),
    sa.Column('intensity_minutes_goal', sa.SmallInteger(), nullable=True),
    sa.Column('floors_ascended', sa.SmallInteger(), nullable=True),
    sa.Column('floors_descended', sa.SmallInteger(), nullable=True),
    sa.Column('floors_ascended_m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('floors_descended_m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('respiration_avg_rpm', sa.SmallInteger(), nullable=True),
    sa.Column('respiration_latest_rpm', sa.SmallInteger(), nullable=True),
    sa.Column('respiration_lowest_rpm', sa.SmallInteger(), nullable=True),
    sa.Column('respiration_highest_rpm', sa.SmallInteger(), nullable=True),
    sa.Column('spo2_avg_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('spo2_latest_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('spo2_lowest_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sleep_score', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sleep_duration_s', sa.Integer(), nullable=True),
    sa.Column('sleep_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sleep_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sleep_deep_s', sa.Integer(), nullable=True),
    sa.Column('sleep_light_s', sa.Integer(), nullable=True),
    sa.Column('sleep_rem_s', sa.Integer(), nullable=True),
    sa.Column('sleep_awake_s', sa.Integer(), nullable=True),
    sa.Column('hrv_rmssd_ms', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hrv_sdnn_ms', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hrv_pnn50_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hrv_weekly_avg_ms', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hrv_baseline_low_ms', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hrv_baseline_high_ms', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hrv_status', sa.Enum('balanced', 'unbalanced', 'low', 'poor', 'unknown', name='hrvstatus', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('hrv_method', sa.Enum('rmssd', 'sdnn', 'pnn50', name='hrvmethod', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('vo2max', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fitness_age_years', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('body_mass_kg', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ftp_watts', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('lactate_threshold_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('training_status', sa.Enum('detraining', 'recovery', 'maintaining', 'productive', 'peaking', 'overreaching', 'unproductive', 'unknown', name='trainingstatus', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('training_load_balance', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('acute_load', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('chronic_load', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('acwr', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('acwr_status', sa.Enum('low', 'optimal', 'high', 'unknown', name='acwrstatus', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('load_aerobic_low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('load_aerobic_high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('load_anaerobic', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('endurance_score', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('readiness_external', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_daily_wellness_athlete_id_athlete')),
    sa.PrimaryKeyConstraint('daily_wellness_id', name=op.f('pk_daily_wellness')),
    sa.UniqueConstraint('athlete_id', 'local_date', name='uq_daily_wellness_athlete_local_date')
    )
    with op.batch_alter_table('daily_wellness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_wellness_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_daily_wellness_athlete_local_date_desc', ['athlete_id', 'local_date'], unique=False)

    op.create_table('digest_subscription',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('cadence', sa.Enum('daily', 'weekly', 'monthly', name='digestcadence', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('weekday', sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='weekday', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('hour_local', sa.SmallInteger(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'cancelled', name='digeststatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_digest_subscription_athlete_id_athlete')),
    sa.PrimaryKeyConstraint('subscription_id', name=op.f('pk_digest_subscription'))
    )
    with op.batch_alter_table('digest_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_subscription_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_digest_subscription_athlete_status', ['athlete_id', 'status'], unique=False)

    op.create_table('fitness_signature',
    sa.Column('signature_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('signature_type', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cp_w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('w_prime_j', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ftp_w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('threshold_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('resting_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('vo2max', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('origin', sa.Enum('measured', 'modeled', 'user_entered', 'source_provided', name='signatureorigin', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('fit_quality', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_fitness_signature_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['signature_type'], ['sport.sport_code'], name=op.f('fk_fitness_signature_signature_type_sport')),
    sa.PrimaryKeyConstraint('signature_id', name=op.f('pk_fitness_signature')),
    sa.UniqueConstraint('athlete_id', 'effective_date', 'signature_type', name='uq_fitness_signature_athlete_date_type')
    )
    with op.batch_alter_table('fitness_signature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitness_signature_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_fitness_signature_athlete_type_effective_desc', ['athlete_id', 'signature_type', 'effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitness_signature_signature_type'), ['signature_type'], unique=False)

    op.create_table('fitness_state_daily',
    sa.Column('fitness_state_daily_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('load_model', sa.String(length=64), nullable=False),
    sa.Column('ctl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('atl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tsb', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_fitness_state_daily_athlete_id_athlete')),
    sa.PrimaryKeyConstraint('fitness_state_daily_id', name=op.f('pk_fitness_state_daily')),
    sa.UniqueConstraint('athlete_id', 'local_date', 'load_model', name='uq_fitness_state_daily_athlete_date_model')
    )
    with op.batch_alter_table('fitness_state_daily', schema=None) as batch_op:
        batch_op.create_index('ix_fitness_state_daily_athlete_date_model', ['athlete_id', 'local_date', 'load_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitness_state_daily_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('goal',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=False),
    sa.Column('goal_type', sa.Enum('event', 'target_metric', 'distance', 'process', 'other', name='goaltype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('target_event', sa.String(length=256), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('target_metric', sa.Enum('cp_w', 'ftp_w', 'distance_m', 'elapsed_time_s', 'vo2max', name='goaltargetmetric', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.Enum('active', 'achieved', 'missed', 'abandoned', name='goalstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_goal_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['sport'], ['sport.sport_code'], name=op.f('fk_goal_sport_sport')),
    sa.PrimaryKeyConstraint('goal_id', name=op.f('pk_goal'))
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_goal_athlete_status_target_date', ['athlete_id', 'status', 'target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_sport'), ['sport'], unique=False)

    op.create_table('notification_route',
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('web', 'email', 'telegram', name='deliverychannel', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('address_ref', sa.String(length=512), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_notification_route_athlete_id_athlete')),
    sa.PrimaryKeyConstraint('route_id', name=op.f('pk_notification_route')),
    sa.UniqueConstraint('athlete_id', 'channel', name='uq_notification_route_athlete_channel')
    )
    with op.batch_alter_table('notification_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_route_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('training_zone_set',
    sa.Column('zone_set_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('zone_kind', sa.Enum('power', 'hr', name='zonekind', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('basis', sa.Enum('absolute', 'relative', name='zonebasis', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('boundaries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_training_zone_set_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['sport'], ['sport.sport_code'], name=op.f('fk_training_zone_set_sport_sport')),
    sa.PrimaryKeyConstraint('zone_set_id', name=op.f('pk_training_zone_set')),
    sa.UniqueConstraint('athlete_id', 'zone_kind', 'effective_date', name='uq_training_zone_set_athlete_kind_effective')
    )
    with op.batch_alter_table('training_zone_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_zone_set_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_training_zone_set_athlete_kind_effective_desc', ['athlete_id', 'zone_kind', 'effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_zone_set_sport'), ['sport'], unique=False)

    op.create_table('wellness_stream_set',
    sa.Column('wellness_stream_set_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('recording_id', sa.SmallInteger(), nullable=False),
    sa.Column('sample_basis', sa.Enum('time', 'distance', 'event', name='samplebasis', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('t0', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_wellness_stream_set_athlete_id_athlete')),
    sa.PrimaryKeyConstraint('wellness_stream_set_id', name=op.f('pk_wellness_stream_set')),
    sa.UniqueConstraint('athlete_id', 'local_date', 'recording_id', name='uq_wellness_stream_set_athlete_date_recording')
    )
    with op.batch_alter_table('wellness_stream_set', schema=None) as batch_op:
        batch_op.create_index('ix_wellness_stream_set_athlete_date_recording', ['athlete_id', 'local_date', 'recording_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wellness_stream_set_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('workout',
    sa.Column('workout_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_workout_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['sport'], ['sport.sport_code'], name=op.f('fk_workout_sport_sport')),
    sa.PrimaryKeyConstraint('workout_id', name=op.f('pk_workout'))
    )
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sport'), ['sport'], unique=False)

    op.create_table('activity_file',
    sa.Column('activity_file_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('object_ref', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.Enum('fit', 'gpx', 'tcx', 'json', 'other', name='activityfileformat', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('source_descriptor_id', sa.Uuid(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id'], name=op.f('fk_activity_file_activity_id_activity')),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_activity_file_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['source_descriptor_id'], ['source_descriptor.source_descriptor_id'], name=op.f('fk_activity_file_source_descriptor_id_source_descriptor')),
    sa.PrimaryKeyConstraint('activity_file_id', name=op.f('pk_activity_file')),
    sa.UniqueConstraint('activity_id', 'source_descriptor_id', 'content_hash', name='uq_activity_file_activity_source_hash')
    )
    with op.batch_alter_table('activity_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_file_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_file_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_file_source_descriptor_id'), ['source_descriptor_id'], unique=False)

    op.create_table('activity_lap',
    sa.Column('activity_lap_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('lap_index', sa.Integer(), nullable=False),
    sa.Column('start_offset_s', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('avg_power_w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_power_w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('avg_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('avg_cadence_rpm', sa.SmallInteger(), nullable=True),
    sa.Column('avg_speed_mps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('elevation_gain_m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id'], name=op.f('fk_activity_lap_activity_id_activity')),
    sa.PrimaryKeyConstraint('activity_lap_id', name=op.f('pk_activity_lap')),
    sa.UniqueConstraint('activity_id', 'lap_index', name='uq_activity_lap_activity_lap_index')
    )
    with op.batch_alter_table('activity_lap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_lap_activity_id'), ['activity_id'], unique=False)

    op.create_table('activity_stream_set',
    sa.Column('stream_set_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('sample_basis', sa.Enum('time', 'distance', 'event', name='samplebasis', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('sample_rate_hz', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('t0', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id'], name=op.f('fk_activity_stream_set_activity_id_activity')),
    sa.PrimaryKeyConstraint('stream_set_id', name=op.f('pk_activity_stream_set')),
    sa.UniqueConstraint('activity_id', name='uq_activity_stream_set_activity')
    )
    with op.batch_alter_table('activity_stream_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_stream_set_activity_id'), ['activity_id'], unique=False)

    op.create_table('derived_activity_metric',
    sa.Column('derived_activity_metric_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('load_model', sa.String(length=64), nullable=False),
    sa.Column('np_w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('if_', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('decoupling_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('variability_index', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('efficiency_factor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('work_above_cp_j', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id'], name=op.f('fk_derived_activity_metric_activity_id_activity')),
    sa.PrimaryKeyConstraint('derived_activity_metric_id', name=op.f('pk_derived_activity_metric')),
    sa.UniqueConstraint('activity_id', 'load_model', name='uq_derived_activity_metric_activity_model')
    )
    with op.batch_alter_table('derived_activity_metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_derived_activity_metric_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index('ix_derived_activity_metric_activity_model', ['activity_id', 'load_model'], unique=False)

    op.create_table('plan',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'superseded', name='planstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_plan_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.goal_id'], name=op.f('fk_plan_goal_id_goal')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_plan'))
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_goal_id'), ['goal_id'], unique=False)

    op.create_table('source_candidate',
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('source_descriptor_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('source_native_id', sa.String(length=256), nullable=False),
    sa.Column('gbo_type', sa.Enum('activity', 'activity_lap', 'activity_file', 'stream_channel', 'daily_wellness', 'wellness_stream_set', 'fitness_signature', name='gbotype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('adapter_version', sa.String(length=64), nullable=True),
    sa.Column('mapping_version', sa.String(length=64), nullable=True),
    sa.Column('trust_profile', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ingest_run_id', sa.Uuid(), nullable=True),
    sa.Column('untrusted_content', sa.Boolean(), nullable=False),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('resolved_activity_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_activity_lap_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_activity_file_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_daily_wellness_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_stream_set_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_wellness_stream_set_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_stream_channel_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_signature_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_source_candidate_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.connection_id'], name=op.f('fk_source_candidate_connection_id_connection')),
    sa.ForeignKeyConstraint(['source_descriptor_id'], ['source_descriptor.source_descriptor_id'], name=op.f('fk_source_candidate_source_descriptor_id_source_descriptor')),
    sa.PrimaryKeyConstraint('source_candidate_id', name=op.f('pk_source_candidate')),
    sa.UniqueConstraint('athlete_id', 'source_descriptor_id', 'source_native_id', 'gbo_type', 'content_hash', name='uq_source_candidate_candidate_key')
    )
    with op.batch_alter_table('source_candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_candidate_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_source_candidate_candidate_key', ['athlete_id', 'source_descriptor_id', 'source_native_id', 'gbo_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_candidate_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index('ix_source_candidate_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_source_candidate_resolved_activity_id', ['resolved_activity_id'], unique=False)
        batch_op.create_index('ix_source_candidate_resolved_daily_wellness_id', ['resolved_daily_wellness_id'], unique=False)
        batch_op.create_index('ix_source_candidate_resolved_signature_id', ['resolved_signature_id'], unique=False)
        batch_op.create_index('ix_source_candidate_resolved_stream_set_id', ['resolved_stream_set_id'], unique=False)
        batch_op.create_index('ix_source_candidate_resolved_wellness_stream_set_id', ['resolved_wellness_stream_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_candidate_source_descriptor_id'), ['source_descriptor_id'], unique=False)

    op.create_table('plan_day',
    sa.Column('plan_day_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('workout_id', sa.Uuid(), nullable=True),
    sa.Column('intent', sa.Enum('easy', 'moderate', 'hard', 'threshold', 'vo2', 'sprint', 'race', 'rest', 'recovery', name='plandayintent', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_plan_day_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], name=op.f('fk_plan_day_plan_id_plan')),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], name=op.f('fk_plan_day_workout_id_workout')),
    sa.PrimaryKeyConstraint('plan_day_id', name=op.f('pk_plan_day')),
    sa.UniqueConstraint('plan_id', 'plan_date', name='uq_plan_day_plan_date')
    )
    with op.batch_alter_table('plan_day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_day_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_plan_day_plan_date', ['plan_id', 'plan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_day_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_day_workout_id'), ['workout_id'], unique=False)

    op.create_table('schedule_adjustment',
    sa.Column('schedule_adjustment_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('move', 'swap_workout', 'shorten', 'lengthen', 'skip', 'rest', 'other', name='adjustmenttype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('target_plan_date', sa.Date(), nullable=True),
    sa.Column('replacement_workout_id', sa.Uuid(), nullable=True),
    sa.Column('origin', sa.Enum('athlete', 'agent', name='adjustmentorigin', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'applied', 'rejected', 'reverted', name='adjustmentstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.athlete_id'], name=op.f('fk_schedule_adjustment_athlete_id_athlete')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], name=op.f('fk_schedule_adjustment_plan_id_plan')),
    sa.ForeignKeyConstraint(['replacement_workout_id'], ['workout.workout_id'], name=op.f('fk_schedule_adjustment_replacement_workout_id_workout')),
    sa.PrimaryKeyConstraint('schedule_adjustment_id', name=op.f('pk_schedule_adjustment'))
    )
    with op.batch_alter_table('schedule_adjustment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_adjustment_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_schedule_adjustment_plan_date_status', ['plan_id', 'plan_date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_adjustment_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_adjustment_replacement_workout_id'), ['replacement_workout_id'], unique=False)

    # ### end Alembic commands ###

    _seed(op)


# --- seed data (registries + built-in file importer) ---


def _seed(op: object) -> None:  # noqa: ANN001 (alembic op proxy)
    """Seed the sport registry (GBO-R16a) and the file_import descriptor (LIN-R1.1).

    Uses lightweight ad-hoc table definitions + ``bulk_insert`` (portable across
    SQLite / PostgreSQL / MariaDB); no vendor SQL.
    """
    now = utcnow()

    # Built-in file importer (LIN-R1.1): EXACTLY ONE descriptor for all ad-hoc uploads.
    source_descriptor = sa.table(
        "source_descriptor",
        sa.column("source_descriptor_id", sa.Uuid()),
        sa.column("source_key", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("kind", sa.String()),
        sa.column("trust_profile", sa.JSON()),
        sa.column("default_fidelity", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(  # type: ignore[attr-defined]
        source_descriptor,
        [
            {
                "source_descriptor_id": FILE_IMPORT_SOURCE_DESCRIPTOR_ID,
                "source_key": "file_import",
                "display_name": "Activity files",
                "kind": "file_upload",
                "trust_profile": {},
                "default_fidelity": None,
                "created_at": now,
                "updated_at": now,
            }
        ],
    )

    # Sport registry (GBO-R16a): the OSS built-in seed members.
    sport = sa.table(
        "sport",
        sa.column("sport_code", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("has_mechanical_power", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(  # type: ignore[attr-defined]
        sport,
        [
            {
                "sport_code": code,
                "display_name": display_name,
                "has_mechanical_power": has_mechanical_power,
                "created_at": now,
                "updated_at": now,
            }
            for code, display_name, has_mechanical_power in SEED_SPORTS
        ],
    )

    # Sub-sport registry (GBO-R16a-ii): each sport gets the mandatory `other` fallback.
    sub_sport = sa.table(
        "sub_sport",
        sa.column("sub_sport_code", sa.String()),
        sa.column("sport_code", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(  # type: ignore[attr-defined]
        sub_sport,
        [
            {
                "sub_sport_code": f"{code}_other",
                "sport_code": code,
                "display_name": "Other",
                "created_at": now,
                "updated_at": now,
            }
            for code, _display_name, _has_mechanical_power in SEED_SPORTS
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_adjustment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_adjustment_replacement_workout_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_adjustment_plan_id'))
        batch_op.drop_index('ix_schedule_adjustment_plan_date_status')
        batch_op.drop_index(batch_op.f('ix_schedule_adjustment_athlete_id'))

    op.drop_table('schedule_adjustment')
    with op.batch_alter_table('plan_day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_day_workout_id'))
        batch_op.drop_index(batch_op.f('ix_plan_day_plan_id'))
        batch_op.drop_index('ix_plan_day_plan_date')
        batch_op.drop_index(batch_op.f('ix_plan_day_athlete_id'))

    op.drop_table('plan_day')
    with op.batch_alter_table('source_candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_candidate_source_descriptor_id'))
        batch_op.drop_index('ix_source_candidate_resolved_wellness_stream_set_id')
        batch_op.drop_index('ix_source_candidate_resolved_stream_set_id')
        batch_op.drop_index('ix_source_candidate_resolved_signature_id')
        batch_op.drop_index('ix_source_candidate_resolved_daily_wellness_id')
        batch_op.drop_index('ix_source_candidate_resolved_activity_id')
        batch_op.drop_index('ix_source_candidate_content_hash')
        batch_op.drop_index(batch_op.f('ix_source_candidate_connection_id'))
        batch_op.drop_index('ix_source_candidate_candidate_key')
        batch_op.drop_index(batch_op.f('ix_source_candidate_athlete_id'))

    op.drop_table('source_candidate')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_goal_id'))
        batch_op.drop_index(batch_op.f('ix_plan_athlete_id'))

    op.drop_table('plan')
    with op.batch_alter_table('derived_activity_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_derived_activity_metric_activity_model')
        batch_op.drop_index(batch_op.f('ix_derived_activity_metric_activity_id'))

    op.drop_table('derived_activity_metric')
    with op.batch_alter_table('activity_stream_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_stream_set_activity_id'))

    op.drop_table('activity_stream_set')
    with op.batch_alter_table('activity_lap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_lap_activity_id'))

    op.drop_table('activity_lap')
    with op.batch_alter_table('activity_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_file_source_descriptor_id'))
        batch_op.drop_index(batch_op.f('ix_activity_file_athlete_id'))
        batch_op.drop_index(batch_op.f('ix_activity_file_activity_id'))

    op.drop_table('activity_file')
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sport'))
        batch_op.drop_index(batch_op.f('ix_workout_athlete_id'))

    op.drop_table('workout')
    with op.batch_alter_table('wellness_stream_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wellness_stream_set_athlete_id'))
        batch_op.drop_index('ix_wellness_stream_set_athlete_date_recording')

    op.drop_table('wellness_stream_set')
    with op.batch_alter_table('training_zone_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_zone_set_sport'))
        batch_op.drop_index('ix_training_zone_set_athlete_kind_effective_desc')
        batch_op.drop_index(batch_op.f('ix_training_zone_set_athlete_id'))

    op.drop_table('training_zone_set')
    with op.batch_alter_table('notification_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_route_athlete_id'))

    op.drop_table('notification_route')
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_sport'))
        batch_op.drop_index('ix_goal_athlete_status_target_date')
        batch_op.drop_index(batch_op.f('ix_goal_athlete_id'))

    op.drop_table('goal')
    with op.batch_alter_table('fitness_state_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_state_daily_athlete_id'))
        batch_op.drop_index('ix_fitness_state_daily_athlete_date_model')

    op.drop_table('fitness_state_daily')
    with op.batch_alter_table('fitness_signature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_signature_signature_type'))
        batch_op.drop_index('ix_fitness_signature_athlete_type_effective_desc')
        batch_op.drop_index(batch_op.f('ix_fitness_signature_athlete_id'))

    op.drop_table('fitness_signature')
    with op.batch_alter_table('digest_subscription', schema=None) as batch_op:
        batch_op.drop_index('ix_digest_subscription_athlete_status')
        batch_op.drop_index(batch_op.f('ix_digest_subscription_athlete_id'))

    op.drop_table('digest_subscription')
    with op.batch_alter_table('daily_wellness', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_wellness_athlete_local_date_desc')
        batch_op.drop_index(batch_op.f('ix_daily_wellness_athlete_id'))

    op.drop_table('daily_wellness')
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_source_descriptor_id'))
        batch_op.drop_index('ix_connection_athlete_source')
        batch_op.drop_index(batch_op.f('ix_connection_athlete_id'))

    op.drop_table('connection')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_sub_sport'))
        batch_op.drop_index(batch_op.f('ix_activity_sport'))
        batch_op.drop_index('ix_activity_athlete_start_time')
        batch_op.drop_index('ix_activity_athlete_sport_start_time')
        batch_op.drop_index(batch_op.f('ix_activity_athlete_id'))

    op.drop_table('activity')
    with op.batch_alter_table('sub_sport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_sport_sport_code'))

    op.drop_table('sub_sport')
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_current_sport'))

    op.drop_table('athlete')
    with op.batch_alter_table('stream_channel', schema=None) as batch_op:
        batch_op.drop_index('ix_stream_channel_stream_set_id')

    op.drop_table('stream_channel')
    op.drop_table('sport')
    op.drop_table('source_descriptor')
    # ### end Alembic commands ###
